name: AgentSwarm Version Management

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: read
  checks: read
  pull-requests: write

jobs:
  version-management:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install semantic-release dependencies
      run: |
        npm install --no-save \
          semantic-release \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github \
          @semantic-release/exec

    - name: Update VERSION file and create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create semantic-release config
        cat > .releaserc.json << 'EOF'
        {
          "branches": ["main"],
          "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            [
              "@semantic-release/exec",
              {
                "prepareCmd": "node -e \"const fs = require('fs'); const versionData = { version: 'v${nextRelease.version}', commit: process.env.GITHUB_SHA, build_date: new Date().toISOString(), build_type: 'production' }; fs.writeFileSync('VERSION', JSON.stringify(versionData, null, 2));\""
              }
            ],
            [
              "@semantic-release/git",
              {
                "assets": ["VERSION"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }
            ],
            "@semantic-release/github"
          ]
        }
        EOF
        
        # Run semantic-release
        npx semantic-release
      continue-on-error: true

    - name: Sync AgentSwarm to template repository
      if: always()
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Get the current version from VERSION file
        AGENTSWARM_VERSION=""
        if [[ -f "VERSION" && -s "VERSION" ]]; then
          AGENTSWARM_VERSION=$(cat VERSION | jq -r '.version // empty' 2>/dev/null || true)
        fi
        
        # Fallback to latest git tag if VERSION file doesn't exist or is empty
        if [[ -z "$AGENTSWARM_VERSION" ]]; then
          AGENTSWARM_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.5.3")
        fi
        
        echo "🚀 Syncing AgentSwarm $AGENTSWARM_VERSION to template..."
        
        # Clone template repository
        git clone https://oauth2:${PAT_TOKEN}@github.com/vanman2024/multi-agent-claude-code /tmp/template
        cd /tmp/template
        
        # Configure git
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        
        # Remove existing agentswarm directory
        rm -rf agentswarm/*
        
        # Copy AgentSwarm files with same exclusions as deploy-to-template.sh
        rsync -a \
          --exclude 'tests/' \
          --exclude 'tests/**' \
          --exclude '*.toml' \
          --exclude '__pycache__/' \
          --exclude '.pytest_cache/' \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude '*.pyc' \
          --exclude '*.pyo' \
          --exclude 'deploy-to-template.sh' \
          --exclude 'scripts/intelligent-auto-deploy.sh' \
          --exclude 'node_modules/' \
          --exclude 'config/' \
          --exclude 'devops/' \
          --exclude 'docs/' \
          --exclude 'specs/' \
          --exclude '.releaserc.json' \
          --exclude '.gitmessage' \
          --exclude 'AGENTS.md' \
          --exclude 'pytest.ini' \
          --exclude 'package.json' \
          --exclude 'package-lock.json' \
          --exclude '.npmrc' \
          --exclude '.env*' \
          --exclude 'venv/' \
          --exclude '.venv/' \
          $GITHUB_WORKSPACE/ agentswarm/
        
        # Copy template version of pyproject.toml if it exists
        if [[ -f "$GITHUB_WORKSPACE/pyproject.toml.template" ]]; then
          cp "$GITHUB_WORKSPACE/pyproject.toml.template" agentswarm/pyproject.toml.template
          echo "✅ Copied pyproject.toml.template for new projects"
        fi
        
        # Commit and push changes
        git add agentswarm/
        if git diff --staged --quiet; then
          echo "✅ No changes to sync"
        else
          git commit -m "chore: sync AgentSwarm to $AGENTSWARM_VERSION

          Automated sync of AgentSwarm component from vanman2024/agentswarm.

          🤖 Generated with [Claude Code](https://claude.ai/code)

          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
          echo "✅ AgentSwarm synced to template successfully"
        fi

    - name: AgentSwarm version management complete
      if: always()
      run: |
        echo "✅ AgentSwarm version management workflow completed"
        echo "📦 AgentSwarm version: $(cat VERSION | jq -r .version 2>/dev/null || echo 'unknown')"
        echo "🚀 Template sync request sent to multi-agent-claude-code"